import type { Metadata } from "next";
import { AppDataProvider } from "@/context/AppContext";
import LayoutWrapper from "@/layout/LayoutWrapper";
import { LoadingProvider } from "@/components/global/Loading/LoadingContext";
import { YesNoPopupProvider } from "@/components/global/Popup/YesNoPopupContext";
import ErrorPopup from "@/components/global/Error/ErrorPopup";
import "./globals.css";


export const metadata: Metadata = {
  title: "HPE BrandLab AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-metricRegular bg-background">
        <AppDataProvider>
          <LoadingProvider>
            <YesNoPopupProvider>
              <ErrorPopup />
              <LayoutWrapper>
                {children}
              </LayoutWrapper>
            </YesNoPopupProvider>
          </LoadingProvider>
        </AppDataProvider>
      </body>
    </html>
  );
}
