import type { Metadata } from "next";
import { AppDataProvider } from "@/context/AppContext";
import "./globals.css";
import LayoutWrapper from "@/layout/LayoutWrapper";
import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "HPE Brand Central AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-inter">
        <AppDataProvider>
          <LayoutWrapper layout="main">
            {children}
          </LayoutWrapper>
        </AppDataProvider>
      </body>
    </html>
  );
}
