export const urls = {
  login: "/user/login",
  finalise: "/user/login/finalise",
  client_select_all: "/client/select/all",
  clientAssetType_select_all: "/clientAssetType/select/all",
  campaign_getProjectsList: "/campaign/getProjectsList",
  campaign_select_all: "campaign/select/all",
  template_select_all: "/template/select/all",
  template_select: "template/select",
  campaign_add: "/campaign/add",
  asset_select_all: "/asset/select/all",
  asset_addWithTemplate: "/asset/addWithTemplate",
  asset_select: "/asset/select",
  asset_getAssetDataUsingAI: "/asset/getAssetDataUsingAI",
  asset_generate: "/asset/generate",
  assetVersionBlock_update: "/AssetVersionBlock/update",
  aiPrompt_Asset_insert: "/aiPrompt/Asset/insert",
  aiPrompt_Asset_update: "/aiPrompt/Asset/update",
  aiPrompt_Campaign_select: "/aiPrompt/Campaign/select",
  aiPrompt_Campaign_insert: "/aiPrompt/Campaign/insert",
  aiPrompt_Campaign_update: "/aiPrompt/Campaign/update",
  aiPrompt_image_update: "/aiPrompt/image/update",
  aiPrompt_GenerateAssetPrompt: "/aiPrompt/GenerateAssetPrompt",
  assetVersionBlock_aiPromptUpdateByTemplateID:
    "/AssetVersionBlock/aiPromptUpdateByTemplateID",
  asset_version_getDataUsingAI: "/asset/version/getDataUsingAI",
  asset_version_generate: "/asset/version/generate",
  asset_version_select: "/asset/version/select",
  asset_version_copy: "/asset/version/copy",
  getCampaigns: "/campaign/select/all",
  getAssetsAllDashboard: "/asset/select/all/Dashboard",
  getuserDetails: "/userProfile/select",
  approval_approver_select_all: "/approval/approver/select/all"
};
